-- ML-294: warm-up exercises for the Warm-ups tool, edited by super admins in Admin -> Warm-ups.
--
-- Each exercise is written for treble-clef brass (brass band parts - cornet, horn, baritone, euphonium
-- and bass all read the same written notes); the tool shows bass clef (trombone, euphonium) by writing
-- the same exercise down a major 9th, so lip slurs stay on the same harmonics. notes is a JSON list of
-- { p: 'G4' | null (rest), d: 'w'|'h'|'q'|'e', dot?: true } - see public/warmups.js, which the server
-- also uses to check every save (bars must add up; written range F#3-C6).
--
-- The 66 exercises seeded below are original to this app (common teaching patterns: long tones,
-- harmonic-series slurs, intervals, tonguing, five-note scales, short tunes) - no copied material.
-- About 19 minutes of playing at their own tempos, so a 4-5 minute warm-up can vary
-- day to day. Grouping by kind: long-tones 10, lip-slurs 12, flexibility 10, articulation 11, fingers 14, melodic 9.

CREATE TABLE warmup_exercises (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (length(title) BETWEEN 1 AND 80),
    kind TEXT NOT NULL CHECK (kind IN ('long-tones', 'lip-slurs', 'flexibility', 'articulation', 'fingers', 'melodic')),
    tip TEXT NOT NULL DEFAULT '' CHECK (length(tip) <= 200),
    notes JSONB NOT NULL,
    beats_per_bar SMALLINT NOT NULL DEFAULT 4 CHECK (beats_per_bar BETWEEN 2 AND 6),
    bpm SMALLINT NOT NULL DEFAULT 72 CHECK (bpm BETWEEN 30 AND 200),
    -- Order within the tool (and admin list); gaps of 10 so one can be moved without renumbering.
    sort_order INTEGER NOT NULL DEFAULT 0,
    -- Switched off: kept, but not shown in the tool.
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_warmup_exercises_order ON warmup_exercises (sort_order, id);

INSERT INTO warmup_exercises (title, kind, tip, notes, beats_per_bar, bpm, sort_order) VALUES
    ('Long tones down from G', 'long-tones', 'Full breath before each note. Keep the sound the same from start to finish.', '[{"p":"G4","d":"w"},{"p":null,"d":"w"},{"p":"F#4","d":"w"},{"p":null,"d":"w"},{"p":"F4","d":"w"},{"p":null,"d":"w"},{"p":"E4","d":"w"},{"p":null,"d":"w"}]'::jsonb, 4, 60, 10),
    ('Long tones up from G', 'long-tones', 'Same size of sound on every note - no push as it goes up.', '[{"p":"G4","d":"w"},{"p":null,"d":"w"},{"p":"G#4","d":"w"},{"p":null,"d":"w"},{"p":"A4","d":"w"},{"p":null,"d":"w"},{"p":"Bb4","d":"w"},{"p":null,"d":"w"}]'::jsonb, 4, 60, 20),
    ('Long tones down from C', 'long-tones', 'Relaxed shoulders; let the air do the work.', '[{"p":"C5","d":"w"},{"p":null,"d":"w"},{"p":"B4","d":"w"},{"p":null,"d":"w"},{"p":"Bb4","d":"w"},{"p":null,"d":"w"},{"p":"A4","d":"w"},{"p":null,"d":"w"}]'::jsonb, 4, 60, 30),
    ('Tuning notes', 'long-tones', 'Listen to the centre of each note. Use the tuner if you like.', '[{"p":"C5","d":"w"},{"p":null,"d":"w"},{"p":"G4","d":"w"},{"p":null,"d":"w"},{"p":"E4","d":"w"},{"p":null,"d":"w"},{"p":"C4","d":"w"},{"p":null,"d":"w"}]'::jsonb, 4, 60, 40),
    ('Low long tones', 'long-tones', 'Open throat, warm air - no pinching in the low notes.', '[{"p":"E4","d":"w"},{"p":null,"d":"w"},{"p":"D4","d":"w"},{"p":null,"d":"w"},{"p":"C4","d":"w"},{"p":null,"d":"w"},{"p":"B3","d":"w"},{"p":null,"d":"w"}]'::jsonb, 4, 56, 50),
    ('Stepping minims', 'long-tones', 'Smooth air between the notes, no bumps.', '[{"p":"G4","d":"h"},{"p":"F4","d":"h"},{"p":"E4","d":"h"},{"p":"F4","d":"h"},{"p":"G4","d":"w"},{"p":"A4","d":"h"},{"p":"G4","d":"h"},{"p":"F4","d":"h"},{"p":"G4","d":"h"},{"p":"A4","d":"w"}]'::jsonb, 4, 66, 60),
    ('Long tones on the harmonics', 'long-tones', 'Each harmonic its own colour; same breath support.', '[{"p":"C4","d":"w"},{"p":null,"d":"w"},{"p":"G4","d":"w"},{"p":null,"d":"w"},{"p":"C5","d":"w"},{"p":null,"d":"w"},{"p":"E5","d":"w"},{"p":null,"d":"w"}]'::jsonb, 4, 60, 70),
    ('Chromatic long tones down from C', 'long-tones', 'Tiny changes of lip, big steady air.', '[{"p":"C5","d":"w"},{"p":null,"d":"w"},{"p":"B4","d":"w"},{"p":null,"d":"w"},{"p":"Bb4","d":"w"},{"p":null,"d":"w"},{"p":"A4","d":"w"},{"p":null,"d":"w"},{"p":"Ab4","d":"w"},{"p":null,"d":"w"},{"p":"G4","d":"w"},{"p":null,"d":"w"}]'::jsonb, 4, 60, 80),
    ('Long tones round D', 'long-tones', 'Hold the middle of the note - not sharp, not flat.', '[{"p":"D5","d":"w"},{"p":null,"d":"w"},{"p":"D4","d":"w"},{"p":null,"d":"w"},{"p":"A4","d":"w"},{"p":null,"d":"w"},{"p":"F#4","d":"w"},{"p":null,"d":"w"}]'::jsonb, 4, 60, 90),
    ('Minim pairs', 'long-tones', 'Two long notes a bar; connect them with the air.', '[{"p":"E4","d":"h"},{"p":"G4","d":"h"},{"p":"F4","d":"h"},{"p":"A4","d":"h"},{"p":"G4","d":"h"},{"p":"B4","d":"h"},{"p":"A4","d":"h"},{"p":"C5","d":"h"},{"p":"C5","d":"w"}]'::jsonb, 4, 66, 100),
    ('Two-note slurs', 'lip-slurs', 'Slur - tongue only the first note. Change the lip, not the air.', '[{"p":"G4","d":"h"},{"p":"C5","d":"h"},{"p":"G4","d":"w"},{"p":"F#4","d":"h"},{"p":"B4","d":"h"},{"p":"F#4","d":"w"},{"p":"F4","d":"h"},{"p":"Bb4","d":"h"},{"p":"F4","d":"w"},{"p":"E4","d":"h"},{"p":"A4","d":"h"},{"p":"E4","d":"w"}]'::jsonb, 4, 72, 110),
    ('Low slurs', 'lip-slurs', 'Keep the corners firm on the way down.', '[{"p":"C4","d":"h"},{"p":"G4","d":"h"},{"p":"C4","d":"w"},{"p":"B3","d":"h"},{"p":"F#4","d":"h"},{"p":"B3","d":"w"},{"p":"Bb3","d":"h"},{"p":"F4","d":"h"},{"p":"Bb3","d":"w"},{"p":"A3","d":"h"},{"p":"E4","d":"h"},{"p":"A3","d":"w"}]'::jsonb, 4, 72, 120),
    ('Three-note slurs', 'lip-slurs', 'Even crotchets; the air keeps moving through the change.', '[{"p":"C4","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"C4","d":"w"},{"p":"B3","d":"q"},{"p":"F#4","d":"q"},{"p":"B4","d":"q"},{"p":"F#4","d":"q"},{"p":"B3","d":"w"},{"p":"Bb3","d":"q"},{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"q"},{"p":"Bb3","d":"w"},{"p":"A3","d":"q"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"q"},{"p":"A3","d":"w"}]'::jsonb, 4, 72, 130),
    ('Upper slurs', 'lip-slurs', 'A little faster air for the top note - don''t press.', '[{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"E5","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"w"},{"p":"F#4","d":"q"},{"p":"B4","d":"q"},{"p":"D#5","d":"q"},{"p":"B4","d":"q"},{"p":"F#4","d":"w"},{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"D5","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"w"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"C#5","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"w"}]'::jsonb, 4, 72, 140),
    ('Quaver slurs', 'lip-slurs', 'Start slowly. Clean changes matter more than speed.', '[{"p":"G4","d":"e"},{"p":"C5","d":"e"},{"p":"G4","d":"e"},{"p":"C5","d":"e"},{"p":"G4","d":"e"},{"p":"C5","d":"e"},{"p":"G4","d":"e"},{"p":"C5","d":"e"},{"p":"G4","d":"w"},{"p":"F#4","d":"e"},{"p":"B4","d":"e"},{"p":"F#4","d":"e"},{"p":"B4","d":"e"},{"p":"F#4","d":"e"},{"p":"B4","d":"e"},{"p":"F#4","d":"e"},{"p":"B4","d":"e"},{"p":"F#4","d":"w"},{"p":"F4","d":"e"},{"p":"Bb4","d":"e"},{"p":"F4","d":"e"},{"p":"Bb4","d":"e"},{"p":"F4","d":"e"},{"p":"Bb4","d":"e"},{"p":"F4","d":"e"},{"p":"Bb4","d":"e"},{"p":"F4","d":"w"}]'::jsonb, 4, 66, 150),
    ('Harmonic ladder', 'lip-slurs', 'Up and down the open harmonics; stay relaxed at the top.', '[{"p":"C4","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"E5","d":"q"},{"p":"G5","d":"w"},{"p":"E5","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"C4","d":"q"},{"p":"C4","d":"w"}]'::jsonb, 4, 66, 160),
    ('Slurs with the second valve', 'lip-slurs', 'Same shape on each valve combination.', '[{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"w"},{"p":"F#4","d":"q"},{"p":"B4","d":"q"},{"p":"F#4","d":"q"},{"p":"B4","d":"q"},{"p":"F#4","d":"w"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"w"}]'::jsonb, 4, 72, 170),
    ('Slurs with the first valve', 'lip-slurs', 'Firm corners; the jaw stays still.', '[{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"w"},{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"D5","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"w"}]'::jsonb, 4, 72, 180),
    ('Slurs with valves 1 and 3', 'lip-slurs', 'The lowest slur - keep the sound open.', '[{"p":"G3","d":"q"},{"p":"D4","d":"q"},{"p":"G4","d":"q"},{"p":"D4","d":"q"},{"p":"G3","d":"w"},{"p":"F#3","d":"q"},{"p":"C#4","d":"q"},{"p":"F#4","d":"q"},{"p":"C#4","d":"q"},{"p":"F#3","d":"w"}]'::jsonb, 4, 72, 190),
    ('Slurs with valves 2 and 3', 'lip-slurs', 'Same air, just the lip changes.', '[{"p":"Ab3","d":"q"},{"p":"Eb4","d":"q"},{"p":"Ab4","d":"q"},{"p":"Eb4","d":"q"},{"p":"Ab3","d":"w"},{"p":"A3","d":"q"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"q"},{"p":"A3","d":"w"}]'::jsonb, 4, 72, 200),
    ('Minim slurs on the top harmonics', 'lip-slurs', 'Slow and relaxed - no pressure.', '[{"p":"C5","d":"h"},{"p":"E5","d":"h"},{"p":"C5","d":"h"},{"p":"G4","d":"h"},{"p":"B4","d":"h"},{"p":"D#5","d":"h"},{"p":"B4","d":"h"},{"p":"F#4","d":"h"},{"p":"C5","d":"w"}]'::jsonb, 4, 66, 210),
    ('Crotchet slurs, all valves', 'lip-slurs', 'Down one valve combination each bar.', '[{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"C4","d":"q"},{"p":"F#4","d":"q"},{"p":"B4","d":"q"},{"p":"F#4","d":"q"},{"p":"B3","d":"q"},{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"q"},{"p":"Bb3","d":"q"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"q"},{"p":"A3","d":"q"},{"p":"G4","d":"w"}]'::jsonb, 4, 72, 220),
    ('Expanding from G', 'flexibility', 'Come back to the same G every time.', '[{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"h"},{"p":"G4","d":"q"},{"p":"B4","d":"q"},{"p":"G4","d":"h"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"h"},{"p":"G4","d":"q"},{"p":"D5","d":"q"},{"p":"G4","d":"h"},{"p":"G4","d":"w"}]'::jsonb, 4, 72, 230),
    ('Expanding down from C', 'flexibility', 'Keep the top C centred as the gap widens.', '[{"p":"C5","d":"q"},{"p":"B4","d":"q"},{"p":"C5","d":"h"},{"p":"C5","d":"q"},{"p":"A4","d":"q"},{"p":"C5","d":"h"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"h"},{"p":"C5","d":"q"},{"p":"F4","d":"q"},{"p":"C5","d":"h"},{"p":"C5","d":"w"}]'::jsonb, 4, 72, 240),
    ('Thirds', 'flexibility', 'Legato - a smooth line through each leap.', '[{"p":"C4","d":"q"},{"p":"E4","d":"q"},{"p":"D4","d":"q"},{"p":"F4","d":"q"},{"p":"E4","d":"q"},{"p":"G4","d":"q"},{"p":"F4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"q"},{"p":"B4","d":"q"},{"p":"A4","d":"q"},{"p":"C5","d":"q"},{"p":"C5","d":"w"}]'::jsonb, 4, 76, 250),
    ('Octave leaps', 'flexibility', 'Aim for the top note with the air, not the mouthpiece.', '[{"p":"C4","d":"h"},{"p":"C5","d":"h"},{"p":"D4","d":"h"},{"p":"D5","d":"h"},{"p":"E4","d":"h"},{"p":"E5","d":"h"},{"p":"C4","d":"w"}]'::jsonb, 4, 66, 260),
    ('Broken chords', 'flexibility', 'Every note the same volume.', '[{"p":"C4","d":"q"},{"p":"E4","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"E4","d":"q"},{"p":"C4","d":"h"},{"p":"F4","d":"q"},{"p":"A4","d":"q"},{"p":"C5","d":"q"},{"p":"A4","d":"q"},{"p":"F4","d":"w"},{"p":"G4","d":"q"},{"p":"B4","d":"q"},{"p":"D5","d":"q"},{"p":"B4","d":"q"},{"p":"G4","d":"w"},{"p":"C5","d":"w"}]'::jsonb, 4, 72, 270),
    ('Fourths and fifths', 'flexibility', 'Open sound on the wide leaps.', '[{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"h"},{"p":"A4","d":"q"},{"p":"D5","d":"q"},{"p":"A4","d":"h"},{"p":"G4","d":"q"},{"p":"D5","d":"q"},{"p":"G4","d":"h"},{"p":"C4","d":"q"},{"p":"G4","d":"q"},{"p":"C4","d":"h"},{"p":"C4","d":"w"}]'::jsonb, 4, 72, 280),
    ('Sixths', 'flexibility', 'Leap with the air, land softly.', '[{"p":"C4","d":"q"},{"p":"A4","d":"q"},{"p":"D4","d":"q"},{"p":"B4","d":"q"},{"p":"E4","d":"q"},{"p":"C5","d":"q"},{"p":"F4","d":"q"},{"p":"D5","d":"q"},{"p":"C5","d":"w"}]'::jsonb, 4, 72, 290),
    ('Expanding from C', 'flexibility', 'Back to the same C each time.', '[{"p":"C4","d":"q"},{"p":"D4","d":"q"},{"p":"C4","d":"h"},{"p":"C4","d":"q"},{"p":"E4","d":"q"},{"p":"C4","d":"h"},{"p":"C4","d":"q"},{"p":"F4","d":"q"},{"p":"C4","d":"h"},{"p":"C4","d":"q"},{"p":"G4","d":"q"},{"p":"C4","d":"h"},{"p":"C4","d":"w"}]'::jsonb, 4, 72, 300),
    ('Broken chord in F', 'flexibility', 'Even notes across the leaps.', '[{"p":"F4","d":"q"},{"p":"A4","d":"q"},{"p":"C5","d":"q"},{"p":"F5","d":"q"},{"p":"C5","d":"q"},{"p":"A4","d":"q"},{"p":"F4","d":"h"},{"p":"Bb4","d":"q"},{"p":"D5","d":"q"},{"p":"F5","d":"q"},{"p":"D5","d":"q"},{"p":"Bb4","d":"w"},{"p":"F4","d":"w"}]'::jsonb, 4, 72, 310),
    ('Arpeggio in G', 'flexibility', 'Smooth over the break.', '[{"p":"G4","d":"q"},{"p":"B4","d":"q"},{"p":"D5","d":"q"},{"p":"G5","d":"q"},{"p":"D5","d":"q"},{"p":"B4","d":"q"},{"p":"G4","d":"h"},{"p":"D4","d":"q"},{"p":"G4","d":"q"},{"p":"B4","d":"q"},{"p":"D5","d":"q"},{"p":"G4","d":"w"}]'::jsonb, 4, 72, 320),
    ('Repeated crotchets', 'articulation', 'Light "too" tongue; the air keeps flowing between notes.', '[{"p":"G4","d":"q"},{"p":"G4","d":"q"},{"p":"G4","d":"q"},{"p":"G4","d":"q"},{"p":"G4","d":"w"},{"p":"F4","d":"q"},{"p":"F4","d":"q"},{"p":"F4","d":"q"},{"p":"F4","d":"q"},{"p":"F4","d":"w"},{"p":"E4","d":"q"},{"p":"E4","d":"q"},{"p":"E4","d":"q"},{"p":"E4","d":"q"},{"p":"E4","d":"w"},{"p":"D4","d":"q"},{"p":"D4","d":"q"},{"p":"D4","d":"q"},{"p":"D4","d":"q"},{"p":"D4","d":"w"}]'::jsonb, 4, 80, 330),
    ('Quavers on one note', 'articulation', 'Even quavers - the tongue stays close to the teeth.', '[{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"w"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"w"},{"p":"C5","d":"e"},{"p":"C5","d":"e"},{"p":"C5","d":"e"},{"p":"C5","d":"e"},{"p":"C5","d":"e"},{"p":"C5","d":"e"},{"p":"C5","d":"e"},{"p":"C5","d":"e"},{"p":"C5","d":"w"}]'::jsonb, 4, 76, 340),
    ('Crotchets and quavers', 'articulation', 'Quavers exactly half a crotchet - count carefully.', '[{"p":"G4","d":"q"},{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"q"},{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"w"},{"p":"A4","d":"q"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"q"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"w"},{"p":"F4","d":"q"},{"p":"F4","d":"e"},{"p":"F4","d":"e"},{"p":"F4","d":"q"},{"p":"F4","d":"e"},{"p":"F4","d":"e"},{"p":"F4","d":"w"}]'::jsonb, 4, 80, 350),
    ('Tongue and move', 'articulation', 'Each pair tongued; step cleanly to the next.', '[{"p":"C5","d":"q"},{"p":"C5","d":"q"},{"p":"B4","d":"q"},{"p":"B4","d":"q"},{"p":"A4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"q"},{"p":"G4","d":"q"},{"p":"F4","d":"q"},{"p":"F4","d":"q"},{"p":"E4","d":"q"},{"p":"E4","d":"q"},{"p":"D4","d":"q"},{"p":"D4","d":"q"},{"p":"C4","d":"h"}]'::jsonb, 4, 80, 360),
    ('Dotted rhythms', 'articulation', 'Long-short: the quaver is short but not clipped.', '[{"p":"G4","d":"q","dot":true},{"p":"G4","d":"e"},{"p":"G4","d":"q","dot":true},{"p":"G4","d":"e"},{"p":"G4","d":"w"},{"p":"E4","d":"q","dot":true},{"p":"E4","d":"e"},{"p":"E4","d":"q","dot":true},{"p":"E4","d":"e"},{"p":"E4","d":"w"},{"p":"C4","d":"q","dot":true},{"p":"C4","d":"e"},{"p":"C4","d":"q","dot":true},{"p":"C4","d":"e"},{"p":"C4","d":"w"}]'::jsonb, 4, 72, 370),
    ('Tonguing on the harmonics', 'articulation', 'Same clean start on every harmonic.', '[{"p":"C4","d":"q"},{"p":"C4","d":"q"},{"p":"G4","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"G4","d":"q"},{"p":"C4","d":"w"}]'::jsonb, 4, 76, 380),
    ('Staccato crotchets', 'articulation', 'Short and light - space between the notes.', '[{"p":"C5","d":"q"},{"p":null,"d":"q"},{"p":"C5","d":"q"},{"p":null,"d":"q"},{"p":"B4","d":"q"},{"p":null,"d":"q"},{"p":"B4","d":"q"},{"p":null,"d":"q"},{"p":"A4","d":"q"},{"p":null,"d":"q"},{"p":"A4","d":"q"},{"p":null,"d":"q"},{"p":"G4","d":"w"}]'::jsonb, 4, 84, 390),
    ('Quavers in F', 'articulation', 'Keep the air moving through the tonguing.', '[{"p":"F4","d":"e"},{"p":"F4","d":"e"},{"p":"F4","d":"e"},{"p":"F4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"Bb4","d":"e"},{"p":"Bb4","d":"e"},{"p":"Bb4","d":"e"},{"p":"Bb4","d":"e"},{"p":"C5","d":"w"}]'::jsonb, 4, 76, 400),
    ('Two quavers and a crotchet', 'articulation', 'Quick-quick-slow, all tongued.', '[{"p":"G4","d":"e"},{"p":"G4","d":"e"},{"p":"G4","d":"q"},{"p":"A4","d":"e"},{"p":"A4","d":"e"},{"p":"A4","d":"q"},{"p":"B4","d":"e"},{"p":"B4","d":"e"},{"p":"B4","d":"q"},{"p":"C5","d":"e"},{"p":"C5","d":"e"},{"p":"C5","d":"q"},{"p":"C5","d":"w"}]'::jsonb, 4, 80, 410),
    ('Waltz tonguing', 'articulation', 'Light second and third beats.', '[{"p":"G4","d":"h"},{"p":"G4","d":"q"},{"p":"A4","d":"h"},{"p":"A4","d":"q"},{"p":"B4","d":"h"},{"p":"B4","d":"q"},{"p":"C5","d":"h","dot":true}]'::jsonb, 3, 88, 420),
    ('Rests and starts', 'articulation', 'Breathe in the rest; start the note cleanly.', '[{"p":"G4","d":"q"},{"p":null,"d":"q"},{"p":"G4","d":"h"},{"p":null,"d":"q"},{"p":"A4","d":"q"},{"p":"A4","d":"h"},{"p":null,"d":"q"},{"p":"B4","d":"q"},{"p":"B4","d":"h"},{"p":"C5","d":"w"}]'::jsonb, 4, 72, 430),
    ('Five-note scale in C', 'fingers', 'Fingers move exactly with the tongue.', '[{"p":"C4","d":"q"},{"p":"D4","d":"q"},{"p":"E4","d":"q"},{"p":"F4","d":"q"},{"p":"G4","d":"q"},{"p":"F4","d":"q"},{"p":"E4","d":"q"},{"p":"D4","d":"q"},{"p":"C4","d":"w"}]'::jsonb, 4, 80, 440),
    ('Five-note scale in F', 'fingers', 'Light fingers - no pressing the valves harder.', '[{"p":"F4","d":"q"},{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"Bb4","d":"q"},{"p":"C5","d":"q"},{"p":"Bb4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"q"},{"p":"F4","d":"w"}]'::jsonb, 4, 80, 450),
    ('Five-note scale in G', 'fingers', 'Watch the F#.', '[{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"B4","d":"q"},{"p":"C5","d":"q"},{"p":"D5","d":"q"},{"p":"C5","d":"q"},{"p":"B4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"w"}]'::jsonb, 4, 80, 460),
    ('Five notes in D minor', 'fingers', 'A darker sound, same steady air.', '[{"p":"D4","d":"q"},{"p":"E4","d":"q"},{"p":"F4","d":"q"},{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"q"},{"p":"F4","d":"q"},{"p":"E4","d":"q"},{"p":"D4","d":"w"}]'::jsonb, 4, 80, 470),
    ('Chromatic from G', 'fingers', 'Every semitone even; fingers quick and together.', '[{"p":"G4","d":"q"},{"p":"G#4","d":"q"},{"p":"A4","d":"q"},{"p":"Bb4","d":"q"},{"p":"B4","d":"q"},{"p":"C5","d":"q"},{"p":"B4","d":"q"},{"p":"Bb4","d":"q"},{"p":"A4","d":"q"},{"p":"G#4","d":"q"},{"p":"G4","d":"h"},{"p":"G4","d":"w"}]'::jsonb, 4, 72, 480),
    ('Quaver scale in C', 'fingers', 'Slur the quavers, one breath per bar.', '[{"p":"C4","d":"e"},{"p":"D4","d":"e"},{"p":"E4","d":"e"},{"p":"F4","d":"e"},{"p":"G4","d":"e"},{"p":"A4","d":"e"},{"p":"B4","d":"e"},{"p":"C5","d":"e"},{"p":"C5","d":"e"},{"p":"B4","d":"e"},{"p":"A4","d":"e"},{"p":"G4","d":"e"},{"p":"F4","d":"e"},{"p":"E4","d":"e"},{"p":"D4","d":"e"},{"p":"C4","d":"e"},{"p":"C4","d":"w"}]'::jsonb, 4, 72, 490),
    ('Five-note scale in D', 'fingers', 'Two sharps: F# and C#.', '[{"p":"D4","d":"q"},{"p":"E4","d":"q"},{"p":"F#4","d":"q"},{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"q"},{"p":"F#4","d":"q"},{"p":"E4","d":"q"},{"p":"D4","d":"w"}]'::jsonb, 4, 80, 500),
    ('Five-note scale in B flat', 'fingers', 'B flat and E flat - steady fingers.', '[{"p":"Bb3","d":"q"},{"p":"C4","d":"q"},{"p":"D4","d":"q"},{"p":"Eb4","d":"q"},{"p":"F4","d":"q"},{"p":"Eb4","d":"q"},{"p":"D4","d":"q"},{"p":"C4","d":"q"},{"p":"Bb3","d":"w"}]'::jsonb, 4, 80, 510),
    ('Five-note scale in E flat', 'fingers', 'Three flats: B, E and A.', '[{"p":"Eb4","d":"q"},{"p":"F4","d":"q"},{"p":"G4","d":"q"},{"p":"Ab4","d":"q"},{"p":"Bb4","d":"q"},{"p":"Ab4","d":"q"},{"p":"G4","d":"q"},{"p":"F4","d":"q"},{"p":"Eb4","d":"w"}]'::jsonb, 4, 80, 520),
    ('Five notes in A minor', 'fingers', 'No sharps or flats - a calm sound.', '[{"p":"A4","d":"q"},{"p":"B4","d":"q"},{"p":"C5","d":"q"},{"p":"D5","d":"q"},{"p":"E5","d":"q"},{"p":"D5","d":"q"},{"p":"C5","d":"q"},{"p":"B4","d":"q"},{"p":"A4","d":"w"}]'::jsonb, 4, 80, 530),
    ('Five notes in E minor', 'fingers', 'Watch the F#.', '[{"p":"E4","d":"q"},{"p":"F#4","d":"q"},{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"B4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"q"},{"p":"F#4","d":"q"},{"p":"E4","d":"w"}]'::jsonb, 4, 80, 540),
    ('Chromatic from C', 'fingers', 'Every semitone even.', '[{"p":"C4","d":"q"},{"p":"C#4","d":"q"},{"p":"D4","d":"q"},{"p":"Eb4","d":"q"},{"p":"E4","d":"q"},{"p":"F4","d":"q"},{"p":"E4","d":"q"},{"p":"Eb4","d":"q"},{"p":"D4","d":"q"},{"p":"C#4","d":"q"},{"p":"C4","d":"h"},{"p":"C4","d":"w"}]'::jsonb, 4, 72, 550),
    ('Scale in thirds in F', 'fingers', 'Up in thirds, then home.', '[{"p":"F4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"q"},{"p":"Bb4","d":"q"},{"p":"A4","d":"q"},{"p":"C5","d":"q"},{"p":"Bb4","d":"q"},{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"F4","d":"q"},{"p":"G4","d":"q"},{"p":"E4","d":"q"},{"p":"F4","d":"w"}]'::jsonb, 4, 76, 560),
    ('Quaver scale in F', 'fingers', 'One breath each bar.', '[{"p":"F4","d":"e"},{"p":"G4","d":"e"},{"p":"A4","d":"e"},{"p":"Bb4","d":"e"},{"p":"C5","d":"e"},{"p":"D5","d":"e"},{"p":"E5","d":"e"},{"p":"F5","d":"e"},{"p":"F5","d":"e"},{"p":"E5","d":"e"},{"p":"D5","d":"e"},{"p":"C5","d":"e"},{"p":"Bb4","d":"e"},{"p":"A4","d":"e"},{"p":"G4","d":"e"},{"p":"F4","d":"e"},{"p":"F4","d":"w"}]'::jsonb, 4, 72, 570),
    ('Morning phrase', 'melodic', 'Sing it in your head first; shape the phrase.', '[{"p":"E4","d":"q"},{"p":"F4","d":"q"},{"p":"G4","d":"h"},{"p":"A4","d":"q"},{"p":"G4","d":"q"},{"p":"E4","d":"h"},{"p":"F4","d":"q"},{"p":"E4","d":"q"},{"p":"D4","d":"q"},{"p":"E4","d":"q"},{"p":"C4","d":"w"}]'::jsonb, 4, 72, 580),
    ('Hymn-like in F', 'melodic', 'Full, warm sound; breathe at the end of each line.', '[{"p":"F4","d":"h"},{"p":"A4","d":"h"},{"p":"C5","d":"h"},{"p":"A4","d":"h"},{"p":"Bb4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"q"},{"p":"F4","d":"q"},{"p":"A4","d":"w"},{"p":"G4","d":"h"},{"p":"Bb4","d":"h"},{"p":"A4","d":"h"},{"p":"F4","d":"h"},{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"q"},{"p":"E4","d":"q"},{"p":"F4","d":"w"}]'::jsonb, 4, 66, 590),
    ('Minor phrase', 'melodic', 'Let the C# lead back to D.', '[{"p":"D4","d":"q"},{"p":"F4","d":"q"},{"p":"A4","d":"h"},{"p":"G4","d":"q"},{"p":"F4","d":"q"},{"p":"E4","d":"h"},{"p":"F4","d":"q"},{"p":"E4","d":"q"},{"p":"D4","d":"q"},{"p":"C#4","d":"q"},{"p":"D4","d":"w"}]'::jsonb, 4, 72, 600),
    ('Little waltz', 'melodic', 'Three in a bar - lean on the first beat.', '[{"p":"C4","d":"h"},{"p":"E4","d":"q"},{"p":"G4","d":"h"},{"p":"E4","d":"q"},{"p":"F4","d":"h"},{"p":"D4","d":"q"},{"p":"C4","d":"h","dot":true}]'::jsonb, 3, 88, 610),
    ('Evening phrase', 'melodic', 'Soft and singing.', '[{"p":"G4","d":"h"},{"p":"E4","d":"h"},{"p":"F4","d":"q"},{"p":"G4","d":"q"},{"p":"A4","d":"h"},{"p":"G4","d":"q"},{"p":"F4","d":"q"},{"p":"E4","d":"q"},{"p":"D4","d":"q"},{"p":"C4","d":"w"}]'::jsonb, 4, 66, 620),
    ('March tune', 'melodic', 'Bright and steady - two in a bar.', '[{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"E4","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"E5","d":"q"},{"p":"D5","d":"h"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"B4","d":"q"},{"p":"C5","d":"h"}]'::jsonb, 2, 96, 630),
    ('Simple song in G', 'melodic', 'Breathe at the end of each two bars.', '[{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"B4","d":"q"},{"p":"G4","d":"q"},{"p":"A4","d":"h"},{"p":"D4","d":"h"},{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"B4","d":"q"},{"p":"C5","d":"q"},{"p":"B4","d":"h"},{"p":"G4","d":"h"}]'::jsonb, 4, 72, 640),
    ('Lullaby in 3', 'melodic', 'Gently rocking.', '[{"p":"E4","d":"h"},{"p":"G4","d":"q"},{"p":"F4","d":"h"},{"p":"D4","d":"q"},{"p":"E4","d":"q"},{"p":"D4","d":"q"},{"p":"C4","d":"q"},{"p":"C4","d":"h","dot":true}]'::jsonb, 3, 76, 650),
    ('Rising line in G', 'melodic', 'Grow gently to the top, then relax.', '[{"p":"G4","d":"h"},{"p":"A4","d":"h"},{"p":"B4","d":"h"},{"p":"C5","d":"h"},{"p":"D5","d":"h"},{"p":"C5","d":"q"},{"p":"B4","d":"q"},{"p":"A4","d":"w"},{"p":"B4","d":"h"},{"p":"A4","d":"h"},{"p":"G4","d":"h"},{"p":"F#4","d":"h"},{"p":"G4","d":"w"}]'::jsonb, 4, 72, 660);

INSERT INTO features (feature_key, name, description, enabled) VALUES
    ('warmups', 'Warm-ups', 'Home screen Warm-ups tool (ML-294): brass warm-up exercises (long tones, lip slurs, flexibility, articulation, finger patterns, easy melodies) on the stave in treble or bass clef, with a metronome that lights the note to play. Exercises are edited in Admin -> Warm-ups.', true)
ON CONFLICT (feature_key) DO NOTHING;
