-- ML-309: the instrument catalogue - a meta table every account picks its instruments from (My account
-- -> Your instruments), so practice time can be measured per instrument (usage stats now; comparing
-- with other players later). Generated from band_instruments_master_catalog.json by
-- scripts/generate-instruments-migration.mjs - edit the catalogue and generate a new migration rather
-- than hand-editing rows here. Upsert on code: ids never change once an account or session uses one.
--
-- theory_clef is the clef the Theory tool starts on for that instrument (brass band treble wins where
-- the catalogue lists one); 'grand' = keyboard, 'none' = unpitched percussion.
CREATE TABLE IF NOT EXISTS instruments (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    pitch_key TEXT,
    sounding_transposition TEXT,
    clef TEXT,
    theory_clef TEXT NOT NULL DEFAULT 'treble' CHECK (theory_clef IN ('treble', 'bass', 'alto', 'tenor', 'grand', 'none')),
    family TEXT NOT NULL,
    subfamily TEXT,
    ensembles TEXT[] NOT NULL DEFAULT '{}',
    role TEXT,
    frequency TEXT,
    notes TEXT,
    sort_order INT NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO instruments (code, name, pitch_key, sounding_transposition, clef, theory_clef, family, subfamily, ensembles, role, frequency, notes, sort_order) VALUES
    ('piccolo_c', 'Piccolo', 'C', 'Sounds 1 octave higher than written', 'Treble', 'treble', 'Woodwind', 'Flute', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Auxiliary / Standard Section Lead High Voice', 'Standard', 'Ubiquitous in concert and military bands for upper-register brilliance and tutti doubling.', 10),
    ('piccolo_db', 'D♭ Piccolo', 'D♭', 'Sounds a minor 9th higher than written', 'Treble', 'treble', 'Woodwind', 'Flute', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Historical Military Band Piccolo', 'Rare / Historical', 'Standard in late 19th and early 20th century American and European military band arrangements (Sousa marches originally scored for D♭ piccolo).', 20),
    ('concert_flute', 'Concert Flute', 'C', 'Concert pitch (non-transposing)', 'Treble', 'treble', 'Woodwind', 'Flute', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Core Woodwind Melody & Color Voice', 'Standard', 'Typically divided into 1st and 2nd flute parts; standard sections contain 4 to 8 players.', 30),
    ('alto_flute', 'Alto Flute', 'G', 'Sounds a perfect 4th lower than written', 'Treble', 'treble', 'Woodwind', 'Flute', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Auxiliary Warm Low Voice', 'Occasional', 'Frequently used in modern symphonic band repertoire for rich, velvety lyrical passages.', 40),
    ('bass_flute', 'Bass Flute', 'C', 'Sounds 1 octave lower than written', 'Treble', 'treble', 'Woodwind', 'Flute', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Auxiliary Deep Tone Color', 'Rare / Extended', 'Found in contemporary large-ensemble works and dedicated flute choir features.', 50),
    ('oboe', 'Oboe', 'C', 'Concert pitch (non-transposing)', 'Treble', 'treble', 'Woodwind', 'Double Reed', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Core Soloist & Harmonic Color Voice', 'Standard', 'Usually 1st and 2nd oboe; primary tuning benchmark instrument in concert bands.', 60),
    ('english_horn', 'English Horn (Cor Anglais)', 'F', 'Sounds a perfect 5th lower than written', 'Treble', 'treble', 'Woodwind', 'Double Reed', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Auxiliary Tenor Double Reed Soloist', 'Common', 'Major expressive voice in masterworks (Holst, Grainger, Maslanka, Reed).', 70),
    ('oboe_d_amore', 'Oboe d''Amore', 'A', 'Sounds a minor 3rd lower than written', 'Treble', 'treble', 'Woodwind', 'Double Reed', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Specialist Mezzo-Soprano Double Reed', 'Rare / Extended', 'Rarely scored in transcriptions (e.g. Ravel, Bach) and select contemporary band works.', 80),
    ('bassoon', 'Bassoon', 'C', 'Concert pitch (non-transposing)', 'Bass / Tenor', 'bass', 'Woodwind', 'Double Reed', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Core Bass & Tenor Woodwind Voice', 'Standard', 'Standard instrumentation calls for Bassoon 1 and 2, reinforcing low clarinets, saxophones, and euphoniums.', 90),
    ('contrabassoon', 'Contrabassoon', 'C', 'Sounds 1 octave lower than written', 'Bass', 'bass', 'Woodwind', 'Double Reed', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Sub-bass Foundation & Dark Accent', 'Occasional', 'Provides foundation pedal reed tone down to sub-contra B♭/A.', 100),
    ('heckelphone', 'Heckelphone', 'C', 'Sounds 1 octave lower than written', 'Treble / Bass', 'treble', 'Woodwind', 'Double Reed', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Rare Baritone Double Reed', 'Rare / Extended', 'Baritone oboe member, occasional appearance in avant-garde and large European wind scores.', 110),
    ('ab_piccolo_clarinet', 'A♭ Piccolo Clarinet', 'A♭', 'Sounds a minor 7th higher than written', 'Treble', 'treble', 'Woodwind', 'Clarinet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'High Sopranino Solo / Color Voice', 'Rare / Historical', 'Featured in traditional Italian and Spanish civil/military bands (banda civica/militare) and clarinet choirs.', 120),
    ('eb_clarinet', 'E♭ Sopranino Clarinet', 'E♭', 'Sounds a minor 3rd higher than written', 'Treble', 'treble', 'Woodwind', 'Clarinet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Standard High Clarinet Voice', 'Standard', 'Crucial lead color in advanced concert band literature, military marches, and wind ensembles.', 130),
    ('d_clarinet', 'D Clarinet', 'D', 'Sounds a major 2nd higher than written', 'Treble', 'treble', 'Woodwind', 'Clarinet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Historical / Classical Sopranino Voice', 'Rare / Historical', 'Seen mainly in older European concert band transcriptions (Strauss, Molter); today almost universally transposed to E♭ clarinet.', 140),
    ('bb_soprano_clarinet', 'B♭ Clarinet (Soprano)', 'B♭', 'Sounds a major 2nd lower than written', 'Treble', 'treble', 'Woodwind', 'Clarinet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Primary Core Woodwind Ensemble Backbone', 'Standard', 'The violin equivalent of the wind band. Divided into 1st, 2nd, and 3rd parts, often with 9–20 players total.', 150),
    ('a_soprano_clarinet', 'A Clarinet', 'A', 'Sounds a minor 3rd lower than written', 'Treble', 'treble', 'Woodwind', 'Clarinet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Occasional Orchestral Adaptation / Soloist', 'Rare / Occasional', 'Standard in orchestras, but occasionally specified in band works (e.g. Percy Grainger, David Maslanka) or orchestral transcriptions.', 160),
    ('basset_horn', 'Basset Horn', 'F', 'Sounds a perfect 5th lower than written', 'Treble', 'treble', 'Woodwind', 'Clarinet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Tenor Auxiliary Clarinet', 'Rare / Occasional', 'Featured in classical transcriptions (Mozart, Mendelssohn) and specialist clarinet choir features.', 170),
    ('eb_alto_clarinet', 'E♭ Alto Clarinet', 'E♭', 'Sounds a major 6th lower than written', 'Treble', 'treble', 'Woodwind', 'Clarinet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Mid-Voice Harmony & Bridge', 'Common', 'Bridges soprano and bass clarinets; standard in American mid-century symphonic band scoring.', 180),
    ('bb_bass_clarinet', 'B♭ Bass Clarinet', 'B♭', 'Sounds a major 9th lower than written (French notation in treble clef)', 'Treble (French notation) / Bass (German notation)', 'treble', 'Woodwind', 'Clarinet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Core Bass Woodwind & Solo Voice', 'Standard', 'Standard section contains 1 to 3 players; critical bridge between woodwinds and brass basses.', 190),
    ('eb_contra_alto_clarinet', 'EE♭ Contra-Alto Clarinet', 'E♭', 'Sounds 1 octave and a major 6th lower than written', 'Treble', 'treble', 'Woodwind', 'Clarinet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Contra-Bass Harmony & Resonance', 'Common', 'Often preferred in academic concert bands for easier response and agility compared to BB♭ contrabass.', 200),
    ('bb_contrabass_clarinet', 'BB♭ Contrabass Clarinet', 'B♭', 'Sounds 2 octaves and a major 2nd lower than written', 'Treble', 'treble', 'Woodwind', 'Clarinet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'True Sub-bass Woodwind Anchor', 'Common', 'Adds profound sub-harmonic depth; capable of descending to sounding B♭0.', 210),
    ('soprillo_saxophone', 'Soprillo Saxophone (Piccolo Saxophone)', 'B♭', 'Sounds 1 octave and a major 2nd higher than written', 'Treble', 'treble', 'Woodwind', 'Saxophone', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Novelty / Extreme High Color', 'Rare / Extended', 'Smallest pitched saxophone (sounding up to F7); rare novelty or saxophone choir feature.', 220),
    ('sopranino_saxophone', 'E♭ Sopranino Saxophone', 'E♭', 'Sounds a minor 3rd higher than written', 'Treble', 'treble', 'Woodwind', 'Saxophone', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Upper Color Accent', 'Occasional', 'Appears in European military band scores and modern saxophone ensemble repertoire.', 230),
    ('bb_soprano_saxophone', 'B♭ Soprano Saxophone', 'B♭', 'Sounds a major 2nd lower than written', 'Treble', 'treble', 'Woodwind', 'Saxophone', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Expressive Soloist & Upper Quartal Voice', 'Common', 'Regularly called for in contemporary concert band literature (Grainger, Husa, Mackey, Ticheli).', 240),
    ('eb_alto_saxophone', 'E♭ Alto Saxophone', 'E♭', 'Sounds a major 6th lower than written', 'Treble', 'treble', 'Woodwind', 'Saxophone', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Core Lead Saxophone Voice', 'Standard', 'Standard instrumentation includes 1st and 2nd Alto Saxophones; versatile melodic and harmonic voice.', 250),
    ('bb_tenor_saxophone', 'B♭ Tenor Saxophone', 'B♭', 'Sounds a major 9th lower than written', 'Treble', 'treble', 'Woodwind', 'Saxophone', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Core Tenor Saxophone Voice', 'Standard', 'Essential middle-register voice, frequently pairing with euphoniums, French horns, and bassoons.', 260),
    ('eb_baritone_saxophone', 'E♭ Baritone Saxophone', 'E♭', 'Sounds 1 octave and a major 6th lower than written', 'Treble', 'treble', 'Woodwind', 'Saxophone', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Core Bass Saxophone & Rhythmic Anchor', 'Standard', 'Usually features a low A key in modern bands; provides punchy bass lines and reed foundation.', 270),
    ('bb_bass_saxophone', 'B♭ Bass Saxophone', 'B♭', 'Sounds 2 octaves and a major 2nd lower than written', 'Treble', 'treble', 'Woodwind', 'Saxophone', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Auxiliary Deep Bass', 'Occasional', 'Common in early 20th century bands (Sousa, Gilmore) and revived in modern concert band scores.', 280),
    ('eb_contrabass_saxophone', 'EE♭ Contrabass Saxophone', 'E♭', 'Sounds 2 octaves and a major 6th lower than written', 'Treble', 'treble', 'Woodwind', 'Saxophone', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Extreme Sub-bass Extension', 'Rare / Extended', 'Gigantic sub-bass saxophone; also seen in modern ''Tubax'' configuration.', 290),
    ('eb_soprano_cornet', 'E♭ Soprano Cornet', 'E♭', 'Sounds a minor 3rd higher than written', 'Treble', 'treble', 'Brass', 'Cornet', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'High Solo Brass Lead & Crown', 'Standard in Brass Band, Common in Wind Band', 'Sole upper-register brass crown in traditional British brass bands (1 player); also used for high color in concert bands.', 300),
    ('bb_cornet', 'B♭ Cornet', 'B♭', 'Sounds a major 2nd lower than written', 'Treble', 'treble', 'Brass', 'Cornet', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Core Melodic Brass Voice', 'Standard', 'In Brass Bands, makes up 9 players (4 Solo Cornets, 1 Repiano, 2 Second Cornets, 2 Third Cornets). In Concert Bands, historically distinct from trumpets (Cornet 1/2).', 310),
    ('bb_repiano_cornet', 'B♭ Repiano Cornet', 'B♭', 'Sounds a major 2nd lower than written', 'Treble', 'treble', 'Brass', 'Cornet', ARRAY['Brass Band']::text[], 'Auxiliary Roving Soloist & Flute/Horn Doubler', 'Standard (Brass Band)', 'Dedicated seat in British brass bands acting as utility soloist and bridge between soprano and lower cornets.', 320),
    ('bb_flugelhorn', 'B♭ Flugelhorn', 'B♭', 'Sounds a major 2nd lower than written', 'Treble', 'treble', 'Brass', 'Flugelhorn', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Mellow Mezzo-Soprano Brass Soloist', 'Standard in Brass Band, Common in Concert Band', '1 player in standard Brass Band (essential bridge to Tenor Horns); frequently used for lyrical solos in concert band works.', 330),
    ('piccolo_trumpet', 'Piccolo Trumpet', 'B♭ / A', 'Sounds a minor 7th (in B♭) or major 6th (in A) higher than written', 'Treble', 'treble', 'Brass', 'Trumpet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'High Clarino Soloist & Brilliance', 'Occasional', 'Four-valved instrument used for clarino baroque transcriptions and contemporary wind ensemble works.', 340),
    ('eb_d_trumpet', 'E♭ / D Trumpet', 'E♭ / D', 'Sounds a minor 3rd (in E♭) or major 2nd (in D) higher than written', 'Treble', 'treble', 'Brass', 'Trumpet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Upper Register Classical Trumpet', 'Occasional', 'Often specified for classical transcriptions (Haydn, Hummel) and high fanfare passages.', 350),
    ('bb_trumpet', 'B♭ Trumpet', 'B♭', 'Sounds a major 2nd lower than written', 'Treble', 'treble', 'Brass', 'Trumpet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Core Melodic & Fanfare Brass Voice', 'Standard (Concert/Wind Band)', 'Standard concert band section comprises 3 parts (often 2–3 players each). Note: Excluded from traditional British brass bands, where cornets reign.', 360),
    ('c_trumpet', 'C Trumpet', 'C', 'Concert pitch (non-transposing)', 'Treble', 'treble', 'Brass', 'Trumpet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Bright Orchestral Trumpet Voice', 'Occasional', 'Frequently utilized by professional wind ensembles and college bands playing orchestral repertoire.', 370),
    ('bass_trumpet', 'Bass Trumpet', 'B♭ / C', 'Sounds a major 9th lower than written (in B♭)', 'Treble / Bass', 'treble', 'Brass', 'Trumpet', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Tenor Brass Fanfare Voice', 'Rare / Extended', 'Occasionally called for in large military bands and works by Stravinsky, Wagner, or modern wind composers.', 380),
    ('eb_tenor_horn', 'E♭ Tenor Horn (Alto Horn)', 'E♭', 'Sounds a major 6th lower than written', 'Treble', 'treble', 'Brass', 'Horn', ARRAY['Brass Band', 'Wind Band / Military Band']::text[], 'Middle Harmonic & Melodic Core (Brass Band)', 'Standard in Brass Band, Common in Military Band', 'Standard in British brass bands (Solo, 1st, and 2nd Tenor Horn). Referred to as ''Alto Horn'' in North America.', 390),
    ('french_horn', 'French Horn (Double Horn)', 'F / B♭', 'Sounds a perfect 5th lower than written (in F)', 'Treble / Bass', 'treble', 'Brass', 'Horn', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Core Harmonic Warmth & Melodic Horn Voice', 'Standard (Concert/Wind Band)', 'Standard section of 4 horns (Horns 1, 2, 3, 4). Excluded from standard British brass bands.', 400),
    ('mellophone', 'F / E♭ Mellophone', 'F / E♭', 'Sounds a perfect 5th lower (in F) or major 6th lower (in E♭)', 'Treble', 'treble', 'Brass', 'Horn', ARRAY['Wind Band / Military Band', 'Marching Band']::text[], 'Forward-Facing Middle Brass', 'Standard in Marching/Outdoor Bands, Historical in Concert Band', 'Commonly replaces French horns in marching wind bands and outdoor military formations.', 410),
    ('wagner_tuba', 'Wagner Tuba (Tenor / Bass)', 'B♭ / F', 'Sounds a major 2nd lower (B♭) or perfect 5th lower (F)', 'Treble / Bass', 'treble', 'Brass', 'Horn', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Deep Noble Brass Color', 'Rare / Extended', 'Played with a horn mouthpiece by French hornists; used in transcriptions (Bruckner, Wagner, Strauss) and extended modern wind works.', 420),
    ('bb_baritone_horn', 'B♭ Baritone Horn', 'B♭', 'Sounds a major 9th lower than written in treble clef (or concert pitch in bass clef)', 'Treble (Brass Band) / Bass (Wind Band)', 'treble', 'Brass', 'Baritone/Euphonium', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Cylindrical/Narrow-Bore Tenor Harmony Voice', 'Standard in Brass Band, Common in Wind Band', 'Standard in British brass bands (1st and 2nd Baritone). Narrower cylindrical bore than euphonium, producing a leaner, lighter tone.', 430),
    ('bb_euphonium', 'B♭ Euphonium', 'B♭', 'Sounds a major 9th lower than written in treble clef (or concert pitch in bass clef)', 'Bass Clef (Concert pitch in Concert Band) / Treble Clef (Transposing in Brass Band)', 'treble', 'Brass', 'Baritone/Euphonium', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Premier Tenor-Baritone Soloist & Tenor Foundation', 'Standard', 'Wide conical bore with warm cello-like timbre. 2 players in brass band (Solo Euphonium & 2nd Euphonium); 2–4 players in concert band.', 440),
    ('alto_trombone', 'Alto Trombone', 'E♭', 'Concert pitch in alto/treble clef, or transposing up a minor 3rd depending on edition', 'Alto / Treble', 'alto', 'Brass', 'Trombone', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Auxiliary High Trombone Voice', 'Occasional', 'Used in early music transcriptions, classical wind serenades, and select modern symphonic wind scores.', 450),
    ('tenor_trombone', 'Tenor Trombone (Slide Trombone)', 'B♭', 'Concert pitch in bass clef (Concert Band); sounds major 9th lower than written in treble clef (Brass Band)', 'Bass / Tenor (Concert Band) / Treble (Brass Band)', 'treble', 'Brass', 'Trombone', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Core Tenor Brass Directional Voice', 'Standard', 'In Brass Band: 1st and 2nd Tenor Trombones reading transposing treble clef. In Concert Band: 1st and 2nd Trombones reading non-transposing bass/tenor clef.', 460),
    ('bass_trombone', 'Bass Trombone', 'B♭ / F / G♭ / D', 'Concert pitch (non-transposing)', 'Bass', 'bass', 'Brass', 'Trombone', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Core Low Brass Voice & Rhythmic Punch', 'Standard', 'Equipped with 1 or 2 rotary/axial valves. Unique in British brass bands as the ONLY brass instrument reading non-transposing bass clef.', 470),
    ('contrabass_trombone', 'Contrabass Trombone', 'BB♭ / F', 'Concert pitch (non-transposing)', 'Bass', 'bass', 'Brass', 'Trombone', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Sub-bass Directional Brass Voice', 'Rare / Extended', 'Double-slide or valve-extended contrabass instrument used in monumental wind ensemble works.', 480),
    ('valve_trombone', 'Valve Trombone', 'B♭', 'Sounds a major 9th lower than written (treble) or concert pitch (bass)', 'Treble / Bass', 'treble', 'Brass', 'Trombone', ARRAY['Wind Band / Military Band', 'Concert Band']::text[], 'Agile Marching & Latin Band Trombone', 'Common in Southern European / Latin American Bands', 'Widely used in Italian, Spanish, Austrian, and Latin American wind bands for rapid valve agility while marching.', 490),
    ('eb_tuba', 'E♭ Tuba (EE♭ Bass)', 'E♭', 'Concert pitch in bass clef (Concert Band); sounds 1 octave + major 6th lower in treble clef (Brass Band)', 'Bass (Concert Band) / Treble (Brass Band)', 'treble', 'Brass', 'Tuba', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Core Bass Foundation', 'Standard', 'Known as ''EE♭ Bass'' in British Brass Bands (2 players). Celebrated for lyrical agility and clear upper-bass definition.', 500),
    ('bb_tuba', 'B♭ Tuba (BB♭ Bass)', 'B♭', 'Concert pitch in bass clef (Concert Band); sounds 2 octaves + major 2nd lower in treble clef (Brass Band)', 'Bass (Concert Band) / Treble (Brass Band)', 'treble', 'Brass', 'Tuba', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Heavy Sub-bass Anchor', 'Standard', 'Known as ''BB♭ Bass'' in British Brass Bands (2 players). Forms the monumental foundation of both brass and wind bands.', 510),
    ('c_tuba', 'C Tuba (CC Tuba)', 'C', 'Concert pitch (non-transposing)', 'Bass', 'bass', 'Brass', 'Tuba', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Orchestral Bass Foundation', 'Common (Professional Wind Ensembles)', 'Standard instrument for orchestral tuba players in the USA, frequently preferred in American collegiate wind ensembles.', 520),
    ('f_tuba', 'F Tuba', 'F', 'Concert pitch (non-transposing)', 'Bass', 'bass', 'Brass', 'Tuba', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Solo & High-Register Tuba Voice', 'Common', 'Used widely for solo repertoire, higher tuba parts, and lighter texture wind ensemble works.', 530),
    ('sousaphone', 'Sousaphone', 'B♭ / E♭', 'Concert pitch (non-transposing bass clef)', 'Bass', 'bass', 'Brass', 'Tuba', ARRAY['Wind Band / Military Band', 'Marching Band']::text[], 'Marching & Military Band Bass Anchor', 'Standard in Marching/Military Bands', 'Designed under John Philip Sousa''s direction to cast warm bass tone upward and over the band.', 540),
    ('helicon', 'Helicon', 'B♭ / E♭ / F', 'Concert pitch (non-transposing bass clef)', 'Bass', 'bass', 'Brass', 'Tuba', ARRAY['Wind Band / Military Band']::text[], 'Historical Mounted/Military Band Bass', 'Occasional / Historical', 'Predecessor to the sousaphone, coiling around the torso; common in European cavalry and military bands.', 550),
    ('double_bass', 'String Bass (Double Bass / Contrabass)', 'C', 'Sounds 1 octave lower than written', 'Bass', 'bass', 'Strings', 'Bowed Strings', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Pizzicato Definition & Low Resonance', 'Standard in Concert Band', 'Standard member of the modern concert band/wind ensemble, providing pizzicato clarity and warm sustained low notes.', 560),
    ('violoncello', 'Cello (Violoncello)', 'C', 'Concert pitch (non-transposing)', 'Bass / Tenor / Treble', 'bass', 'Strings', 'Bowed Strings', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Mid-Bass Melodic Voice', 'Rare / Regional', 'Standard in traditional Spanish wind bands (bandas de música) and Italian municipal bands; occasional guest in symphonic wind works.', 570),
    ('concert_harp', 'Concert Harp', 'C (Diatonic with 7 double-action pedals)', 'Concert pitch (non-transposing)', 'Grand Staff (Treble and Bass)', 'grand', 'Strings', 'Plucked Strings', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Arpeggiated Color & Delicate Accents', 'Common in Advanced Wind Literature', 'Featured extensively in contemporary masterworks (Grainger, Persichetti, Husa, Barnes, Whitacre).', 580),
    ('electric_bass', 'Electric Bass Guitar', 'C', 'Sounds 1 octave lower than written', 'Bass', 'bass', 'Strings', 'Plucked Strings (Electric)', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Modern Rhythm & Punch', 'Common in Pops & Contemporary Literature', 'Often doubles or replaces the tuba/double bass in jazz, pop, Broadway, and wind rock settings.', 590),
    ('piano', 'Concert Grand Piano', 'C', 'Concert pitch (non-transposing)', 'Grand Staff (Treble and Bass)', 'grand', 'Keyboard', 'Keyboard / Percussion', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Harmonic Backbone, Percussive Attack & Soloist', 'Standard in Contemporary Literature', 'Vital orchestral texture in 20th and 21st-century wind band repertoire.', 600),
    ('celesta', 'Celesta', 'C', 'Sounds 1 octave higher than written', 'Grand Staff (Treble and Bass)', 'grand', 'Keyboard', 'Keyboard / Metallophone', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Ethereal Sparkle & Color', 'Occasional', 'Steel plates struck by felt hammers, operated via keyboard; used for delicate fairy-like textures.', 610),
    ('synthesizer_organ', 'Synthesizer / Electronic Organ', 'C', 'Concert pitch (transposition user-defined)', 'Grand Staff', 'grand', 'Keyboard', 'Electronic', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Sub-pedal Tones & Electronic Effects', 'Occasional', 'Used for pipe organ emulations, sub-bass 32'' pedal points, and atmospheric sound design.', 620),
    ('timpani', 'Timpani (Kettledrums)', 'Tuned to pitch (typically set of 4 or 5 drums: 32", 29", 26", 23", 20")', 'Concert pitch (non-transposing)', 'Bass', 'bass', 'Percussion', 'Tuned Percussion (Membranophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Core Harmonic Bass Rhythms & Dynamic Climax', 'Standard', 'Crucial anchor in both brass bands and concert bands. Pitch range typically covers D2 to A3.', 630),
    ('glockenspiel', 'Glockenspiel (Orchestra Bells)', 'C (Tuned steel bars)', 'Sounds 2 octaves higher than written', 'Treble', 'treble', 'Percussion', 'Tuned Percussion (Metallophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Upper Harmonic Sparkle & Melody Reinforcement', 'Standard', 'Penetrating high metallic bell tone, often doubling upper woodwinds or soprano brass.', 640),
    ('xylophone', 'Xylophone', 'C (Tuned rosewood/synthetic bars)', 'Sounds 1 octave higher than written', 'Treble', 'treble', 'Percussion', 'Tuned Percussion (Idiophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Sharp Articulation & Rapid Melodic Runs', 'Standard', 'Bright, sharp acoustic attack; essential in both modern concert band and brass band percussion sections.', 650),
    ('marimba', 'Marimba', 'C (Tuned rosewood/padauk bars, usually 4.3 or 5.0 octaves)', 'Concert pitch (non-transposing)', 'Grand Staff (Treble and Bass)', 'grand', 'Percussion', 'Tuned Percussion (Idiophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Warm Resonant Chords & Rapid Keyboard Runs', 'Standard in Modern Band Repertoire', 'Deep, warm, resonant acoustic timbre; foundational voice in modern percussion writing.', 660),
    ('vibraphone', 'Vibraphone', 'C (Tuned aluminum alloy bars, 3.0 octaves)', 'Concert pitch (non-transposing)', 'Treble', 'treble', 'Percussion', 'Tuned Percussion (Metallophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Lyrical Sustained Chords & Motor Vibrato Effects', 'Standard in Modern Band Repertoire', 'Equipped with motorized rotating butterflies in resonator tubes and a damper pedal.', 670),
    ('tubular_bells', 'Tubular Bells (Chimes)', 'C (Tuned brass tubes, usually C4 to F5 / G5)', 'Concert pitch (non-transposing)', 'Treble', 'treble', 'Percussion', 'Tuned Percussion (Metallophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Church Bell Emulation & Majestic Fanfares', 'Standard', 'Simulates real church bells; prominent in climaxes and ceremonial marches.', 680),
    ('crotales', 'Crotales (Antique Cymbals)', 'C (Tuned bronze discs, 1 or 2 octaves)', 'Sounds 2 octaves higher than written', 'Treble', 'treble', 'Percussion', 'Tuned Percussion (Metallophone)', ARRAY['Concert Band', 'Wind Band / Military Band']::text[], 'Pristine High Shimmer & Bowed Metallic Textures', 'Common in Contemporary Literature', 'Can be struck with hard mallets or bowed with a double bass bow for eerie, shimmering harmonics.', 690),
    ('snare_drum', 'Snare Drum', 'Indefinite Pitch (Non-tuned)', 'Indefinite pitch', 'Neutral / Percussion Clef', 'none', 'Percussion', 'Unpitched Percussion (Membranophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Primary Rhythmic Drive & Military Rudiments', 'Standard', 'Foundational instrument in all band types; metal/gut snares provide crisp articulation.', 700),
    ('bass_drum', 'Concert Bass Drum (Gran Cassa)', 'Indefinite Pitch (Low resonance)', 'Indefinite pitch', 'Neutral / Percussion Clef', 'none', 'Percussion', 'Unpitched Percussion (Membranophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Deep Acoustic Pulse & Explosive Impact', 'Standard', 'Large suspended calfskin or plastic head drum providing foundational dynamic weight.', 710),
    ('clash_cymbals', 'Clash Cymbals (Crash Cymbals / Hand Cymbals)', 'Indefinite Pitch (High metallic spectrum)', 'Indefinite pitch', 'Neutral / Percussion Clef', 'none', 'Percussion', 'Unpitched Percussion (Idiophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Dynamic Climax & March Accents', 'Standard', 'Hand-held paired bronze cymbals (typically 18" to 22" Viennese or French crash).', 720),
    ('suspended_cymbal', 'Suspended Cymbal', 'Indefinite Pitch', 'Indefinite pitch', 'Neutral / Percussion Clef', 'none', 'Percussion', 'Unpitched Percussion (Idiophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Atmospheric Crescendos & Accents', 'Standard', 'Played with yarn/felt mallets, drumsticks, or scraped with a triangle beater/coin.', 730),
    ('tam_tam', 'Tam-Tam (Gong)', 'Indefinite Pitch (Deep fundamental spectrum)', 'Indefinite pitch', 'Neutral / Percussion Clef', 'none', 'Percussion', 'Unpitched Percussion (Idiophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Dramatic Cataclysm & Solemn Resonances', 'Standard', 'Unpitched, flat-faced hammered bronze disc; provides colossal dramatic crashes and quiet omens.', 740),
    ('triangle', 'Triangle', 'Indefinite Pitch (High metallic overtone)', 'Indefinite pitch', 'Neutral / Percussion Clef', 'none', 'Percussion', 'Unpitched Percussion (Idiophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'High Crystalline Punctuation & Shimmer', 'Standard', 'Steel bar bent into an open triangle; cuts clearly through full fortissimo tutti.', 750),
    ('tambourine', 'Tambourine', 'Indefinite Pitch', 'Indefinite pitch', 'Neutral / Percussion Clef', 'none', 'Percussion', 'Unpitched Percussion (Membranophone/Idiophone)', ARRAY['Brass Band', 'Concert Band', 'Wind Band / Military Band']::text[], 'Rhythmic Color & Festive Accents', 'Standard', 'Wood shell with calfskin head and metal jingles; executed with thumb rolls, shakes, and knee-fist strikes.', 760)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name, pitch_key = EXCLUDED.pitch_key, sounding_transposition = EXCLUDED.sounding_transposition,
    clef = EXCLUDED.clef, theory_clef = EXCLUDED.theory_clef, family = EXCLUDED.family, subfamily = EXCLUDED.subfamily,
    ensembles = EXCLUDED.ensembles, role = EXCLUDED.role, frequency = EXCLUDED.frequency, notes = EXCLUDED.notes,
    sort_order = EXCLUDED.sort_order;

-- The instruments an account plays; at most one is its main instrument (the default for new sessions
-- and for the Theory tool).
CREATE TABLE IF NOT EXISTS account_instruments (
    account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    instrument_id BIGINT NOT NULL REFERENCES instruments(id),
    is_primary BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (account_id, instrument_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS account_instruments_one_primary ON account_instruments (account_id) WHERE is_primary;

-- Which instrument a practice session was on. Null for sessions logged before this, or by an account
-- with no instruments set. Set server-side (POST /api/sessions) to the chosen or main instrument.
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS instrument_id BIGINT REFERENCES instruments(id);
CREATE INDEX IF NOT EXISTS sessions_instrument_id ON sessions (instrument_id) WHERE instrument_id IS NOT NULL;
