-- ML-361: slurs on the seeded Lip slurs and Flexibility warm-ups. A note can now carry "sl": true -
-- slurred to the next note (public/warmups.js; the stave draws it with standard engraving). The rule,
-- agreed with the owner: each bar's notes are slurred, carried on to the next bar when that bar is a
-- single held note. Long tones, articulation (the tonguing kind), finger patterns and easy melodies get
-- none. Each exercise is updated only if its notes are still exactly as seeded in 055, so one an admin
-- has changed is left as it is (add its slurs in Admin -> Warm-ups).

-- Two-note slurs: G4h^ C5h^ G4w F#4h^ B4h^ F#4w F4h^ Bb4h^ F4w E4h^ A4h^ E4w
UPDATE warmup_exercises SET notes = '[{"p":"G4","d":"h","sl":true},{"p":"C5","d":"h","sl":true},{"p":"G4","d":"w"},{"p":"F#4","d":"h","sl":true},{"p":"B4","d":"h","sl":true},{"p":"F#4","d":"w"},{"p":"F4","d":"h","sl":true},{"p":"Bb4","d":"h","sl":true},{"p":"F4","d":"w"},{"p":"E4","d":"h","sl":true},{"p":"A4","d":"h","sl":true},{"p":"E4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Two-note slurs' AND kind = 'lip-slurs' AND notes = '[{"p":"G4","d":"h"},{"p":"C5","d":"h"},{"p":"G4","d":"w"},{"p":"F#4","d":"h"},{"p":"B4","d":"h"},{"p":"F#4","d":"w"},{"p":"F4","d":"h"},{"p":"Bb4","d":"h"},{"p":"F4","d":"w"},{"p":"E4","d":"h"},{"p":"A4","d":"h"},{"p":"E4","d":"w"}]'::jsonb;

-- Low slurs: C4h^ G4h^ C4w B3h^ F#4h^ B3w Bb3h^ F4h^ Bb3w A3h^ E4h^ A3w
UPDATE warmup_exercises SET notes = '[{"p":"C4","d":"h","sl":true},{"p":"G4","d":"h","sl":true},{"p":"C4","d":"w"},{"p":"B3","d":"h","sl":true},{"p":"F#4","d":"h","sl":true},{"p":"B3","d":"w"},{"p":"Bb3","d":"h","sl":true},{"p":"F4","d":"h","sl":true},{"p":"Bb3","d":"w"},{"p":"A3","d":"h","sl":true},{"p":"E4","d":"h","sl":true},{"p":"A3","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Low slurs' AND kind = 'lip-slurs' AND notes = '[{"p":"C4","d":"h"},{"p":"G4","d":"h"},{"p":"C4","d":"w"},{"p":"B3","d":"h"},{"p":"F#4","d":"h"},{"p":"B3","d":"w"},{"p":"Bb3","d":"h"},{"p":"F4","d":"h"},{"p":"Bb3","d":"w"},{"p":"A3","d":"h"},{"p":"E4","d":"h"},{"p":"A3","d":"w"}]'::jsonb;

-- Three-note slurs: C4q^ G4q^ C5q^ G4q^ C4w B3q^ F#4q^ B4q^ F#4q^ B3w Bb3q^ F4q^ Bb4q^ F4q^ Bb3w A3q^ E4q^ A4q^ E4q^ A3w
UPDATE warmup_exercises SET notes = '[{"p":"C4","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"C4","d":"w"},{"p":"B3","d":"q","sl":true},{"p":"F#4","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"F#4","d":"q","sl":true},{"p":"B3","d":"w"},{"p":"Bb3","d":"q","sl":true},{"p":"F4","d":"q","sl":true},{"p":"Bb4","d":"q","sl":true},{"p":"F4","d":"q","sl":true},{"p":"Bb3","d":"w"},{"p":"A3","d":"q","sl":true},{"p":"E4","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"E4","d":"q","sl":true},{"p":"A3","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Three-note slurs' AND kind = 'lip-slurs' AND notes = '[{"p":"C4","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"C4","d":"w"},{"p":"B3","d":"q"},{"p":"F#4","d":"q"},{"p":"B4","d":"q"},{"p":"F#4","d":"q"},{"p":"B3","d":"w"},{"p":"Bb3","d":"q"},{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"q"},{"p":"Bb3","d":"w"},{"p":"A3","d":"q"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"q"},{"p":"A3","d":"w"}]'::jsonb;

-- Upper slurs: G4q^ C5q^ E5q^ C5q^ G4w F#4q^ B4q^ D#5q^ B4q^ F#4w F4q^ Bb4q^ D5q^ Bb4q^ F4w E4q^ A4q^ C#5q^ A4q^ E4w
UPDATE warmup_exercises SET notes = '[{"p":"G4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"E5","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"G4","d":"w"},{"p":"F#4","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"D#5","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"F#4","d":"w"},{"p":"F4","d":"q","sl":true},{"p":"Bb4","d":"q","sl":true},{"p":"D5","d":"q","sl":true},{"p":"Bb4","d":"q","sl":true},{"p":"F4","d":"w"},{"p":"E4","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"C#5","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"E4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Upper slurs' AND kind = 'lip-slurs' AND notes = '[{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"E5","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"w"},{"p":"F#4","d":"q"},{"p":"B4","d":"q"},{"p":"D#5","d":"q"},{"p":"B4","d":"q"},{"p":"F#4","d":"w"},{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"D5","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"w"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"C#5","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"w"}]'::jsonb;

-- Quaver slurs: G4e^ C5e^ G4e^ C5e^ G4e^ C5e^ G4e^ C5e^ G4w F#4e^ B4e^ F#4e^ B4e^ F#4e^ B4e^ F#4e^ B4e^ F#4w F4e^ Bb4e^ F4e^ Bb4e^ F4e^ Bb4e^ F4e^ Bb4e^ F4w
UPDATE warmup_exercises SET notes = '[{"p":"G4","d":"e","sl":true},{"p":"C5","d":"e","sl":true},{"p":"G4","d":"e","sl":true},{"p":"C5","d":"e","sl":true},{"p":"G4","d":"e","sl":true},{"p":"C5","d":"e","sl":true},{"p":"G4","d":"e","sl":true},{"p":"C5","d":"e","sl":true},{"p":"G4","d":"w"},{"p":"F#4","d":"e","sl":true},{"p":"B4","d":"e","sl":true},{"p":"F#4","d":"e","sl":true},{"p":"B4","d":"e","sl":true},{"p":"F#4","d":"e","sl":true},{"p":"B4","d":"e","sl":true},{"p":"F#4","d":"e","sl":true},{"p":"B4","d":"e","sl":true},{"p":"F#4","d":"w"},{"p":"F4","d":"e","sl":true},{"p":"Bb4","d":"e","sl":true},{"p":"F4","d":"e","sl":true},{"p":"Bb4","d":"e","sl":true},{"p":"F4","d":"e","sl":true},{"p":"Bb4","d":"e","sl":true},{"p":"F4","d":"e","sl":true},{"p":"Bb4","d":"e","sl":true},{"p":"F4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Quaver slurs' AND kind = 'lip-slurs' AND notes = '[{"p":"G4","d":"e"},{"p":"C5","d":"e"},{"p":"G4","d":"e"},{"p":"C5","d":"e"},{"p":"G4","d":"e"},{"p":"C5","d":"e"},{"p":"G4","d":"e"},{"p":"C5","d":"e"},{"p":"G4","d":"w"},{"p":"F#4","d":"e"},{"p":"B4","d":"e"},{"p":"F#4","d":"e"},{"p":"B4","d":"e"},{"p":"F#4","d":"e"},{"p":"B4","d":"e"},{"p":"F#4","d":"e"},{"p":"B4","d":"e"},{"p":"F#4","d":"w"},{"p":"F4","d":"e"},{"p":"Bb4","d":"e"},{"p":"F4","d":"e"},{"p":"Bb4","d":"e"},{"p":"F4","d":"e"},{"p":"Bb4","d":"e"},{"p":"F4","d":"e"},{"p":"Bb4","d":"e"},{"p":"F4","d":"w"}]'::jsonb;

-- Harmonic ladder: C4q^ G4q^ C5q^ E5q^ G5w E5q^ C5q^ G4q^ C4q^ C4w
UPDATE warmup_exercises SET notes = '[{"p":"C4","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"E5","d":"q","sl":true},{"p":"G5","d":"w"},{"p":"E5","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"C4","d":"q","sl":true},{"p":"C4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Harmonic ladder' AND kind = 'lip-slurs' AND notes = '[{"p":"C4","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"E5","d":"q"},{"p":"G5","d":"w"},{"p":"E5","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"C4","d":"q"},{"p":"C4","d":"w"}]'::jsonb;

-- Slurs with the second valve: G4q^ C5q^ G4q^ C5q^ G4w F#4q^ B4q^ F#4q^ B4q^ F#4w E4q^ A4q^ E4q^ A4q^ E4w
UPDATE warmup_exercises SET notes = '[{"p":"G4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"G4","d":"w"},{"p":"F#4","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"F#4","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"F#4","d":"w"},{"p":"E4","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"E4","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"E4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Slurs with the second valve' AND kind = 'lip-slurs' AND notes = '[{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"w"},{"p":"F#4","d":"q"},{"p":"B4","d":"q"},{"p":"F#4","d":"q"},{"p":"B4","d":"q"},{"p":"F#4","d":"w"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"w"}]'::jsonb;

-- Slurs with the first valve: F4q^ Bb4q^ F4q^ Bb4q^ F4w F4q^ Bb4q^ D5q^ Bb4q^ F4w
UPDATE warmup_exercises SET notes = '[{"p":"F4","d":"q","sl":true},{"p":"Bb4","d":"q","sl":true},{"p":"F4","d":"q","sl":true},{"p":"Bb4","d":"q","sl":true},{"p":"F4","d":"w"},{"p":"F4","d":"q","sl":true},{"p":"Bb4","d":"q","sl":true},{"p":"D5","d":"q","sl":true},{"p":"Bb4","d":"q","sl":true},{"p":"F4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Slurs with the first valve' AND kind = 'lip-slurs' AND notes = '[{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"w"},{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"D5","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"w"}]'::jsonb;

-- Slurs with valves 1 and 3: G3q^ D4q^ G4q^ D4q^ G3w F#3q^ C#4q^ F#4q^ C#4q^ F#3w
UPDATE warmup_exercises SET notes = '[{"p":"G3","d":"q","sl":true},{"p":"D4","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"D4","d":"q","sl":true},{"p":"G3","d":"w"},{"p":"F#3","d":"q","sl":true},{"p":"C#4","d":"q","sl":true},{"p":"F#4","d":"q","sl":true},{"p":"C#4","d":"q","sl":true},{"p":"F#3","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Slurs with valves 1 and 3' AND kind = 'lip-slurs' AND notes = '[{"p":"G3","d":"q"},{"p":"D4","d":"q"},{"p":"G4","d":"q"},{"p":"D4","d":"q"},{"p":"G3","d":"w"},{"p":"F#3","d":"q"},{"p":"C#4","d":"q"},{"p":"F#4","d":"q"},{"p":"C#4","d":"q"},{"p":"F#3","d":"w"}]'::jsonb;

-- Slurs with valves 2 and 3: Ab3q^ Eb4q^ Ab4q^ Eb4q^ Ab3w A3q^ E4q^ A4q^ E4q^ A3w
UPDATE warmup_exercises SET notes = '[{"p":"Ab3","d":"q","sl":true},{"p":"Eb4","d":"q","sl":true},{"p":"Ab4","d":"q","sl":true},{"p":"Eb4","d":"q","sl":true},{"p":"Ab3","d":"w"},{"p":"A3","d":"q","sl":true},{"p":"E4","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"E4","d":"q","sl":true},{"p":"A3","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Slurs with valves 2 and 3' AND kind = 'lip-slurs' AND notes = '[{"p":"Ab3","d":"q"},{"p":"Eb4","d":"q"},{"p":"Ab4","d":"q"},{"p":"Eb4","d":"q"},{"p":"Ab3","d":"w"},{"p":"A3","d":"q"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"q"},{"p":"A3","d":"w"}]'::jsonb;

-- Minim slurs on the top harmonics: C5h^ E5h C5h^ G4h B4h^ D#5h B4h^ F#4h^ C5w
UPDATE warmup_exercises SET notes = '[{"p":"C5","d":"h","sl":true},{"p":"E5","d":"h"},{"p":"C5","d":"h","sl":true},{"p":"G4","d":"h"},{"p":"B4","d":"h","sl":true},{"p":"D#5","d":"h"},{"p":"B4","d":"h","sl":true},{"p":"F#4","d":"h","sl":true},{"p":"C5","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Minim slurs on the top harmonics' AND kind = 'lip-slurs' AND notes = '[{"p":"C5","d":"h"},{"p":"E5","d":"h"},{"p":"C5","d":"h"},{"p":"G4","d":"h"},{"p":"B4","d":"h"},{"p":"D#5","d":"h"},{"p":"B4","d":"h"},{"p":"F#4","d":"h"},{"p":"C5","d":"w"}]'::jsonb;

-- Crotchet slurs, all valves: G4q^ C5q^ G4q^ C4q F#4q^ B4q^ F#4q^ B3q F4q^ Bb4q^ F4q^ Bb3q E4q^ A4q^ E4q^ A3q^ G4w
UPDATE warmup_exercises SET notes = '[{"p":"G4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"C4","d":"q"},{"p":"F#4","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"F#4","d":"q","sl":true},{"p":"B3","d":"q"},{"p":"F4","d":"q","sl":true},{"p":"Bb4","d":"q","sl":true},{"p":"F4","d":"q","sl":true},{"p":"Bb3","d":"q"},{"p":"E4","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"E4","d":"q","sl":true},{"p":"A3","d":"q","sl":true},{"p":"G4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Crotchet slurs, all valves' AND kind = 'lip-slurs' AND notes = '[{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"C4","d":"q"},{"p":"F#4","d":"q"},{"p":"B4","d":"q"},{"p":"F#4","d":"q"},{"p":"B3","d":"q"},{"p":"F4","d":"q"},{"p":"Bb4","d":"q"},{"p":"F4","d":"q"},{"p":"Bb3","d":"q"},{"p":"E4","d":"q"},{"p":"A4","d":"q"},{"p":"E4","d":"q"},{"p":"A3","d":"q"},{"p":"G4","d":"w"}]'::jsonb;

-- Expanding from G: G4q^ A4q^ G4h G4q^ B4q^ G4h G4q^ C5q^ G4h G4q^ D5q^ G4h^ G4w
UPDATE warmup_exercises SET notes = '[{"p":"G4","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"G4","d":"h"},{"p":"G4","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"G4","d":"h"},{"p":"G4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"G4","d":"h"},{"p":"G4","d":"q","sl":true},{"p":"D5","d":"q","sl":true},{"p":"G4","d":"h","sl":true},{"p":"G4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Expanding from G' AND kind = 'flexibility' AND notes = '[{"p":"G4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"h"},{"p":"G4","d":"q"},{"p":"B4","d":"q"},{"p":"G4","d":"h"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"h"},{"p":"G4","d":"q"},{"p":"D5","d":"q"},{"p":"G4","d":"h"},{"p":"G4","d":"w"}]'::jsonb;

-- Expanding down from C: C5q^ B4q^ C5h C5q^ A4q^ C5h C5q^ G4q^ C5h C5q^ F4q^ C5h^ C5w
UPDATE warmup_exercises SET notes = '[{"p":"C5","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"C5","d":"h"},{"p":"C5","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"C5","d":"h"},{"p":"C5","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"C5","d":"h"},{"p":"C5","d":"q","sl":true},{"p":"F4","d":"q","sl":true},{"p":"C5","d":"h","sl":true},{"p":"C5","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Expanding down from C' AND kind = 'flexibility' AND notes = '[{"p":"C5","d":"q"},{"p":"B4","d":"q"},{"p":"C5","d":"h"},{"p":"C5","d":"q"},{"p":"A4","d":"q"},{"p":"C5","d":"h"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"h"},{"p":"C5","d":"q"},{"p":"F4","d":"q"},{"p":"C5","d":"h"},{"p":"C5","d":"w"}]'::jsonb;

-- Thirds: C4q^ E4q^ D4q^ F4q E4q^ G4q^ F4q^ A4q G4q^ B4q^ A4q^ C5q^ C5w
UPDATE warmup_exercises SET notes = '[{"p":"C4","d":"q","sl":true},{"p":"E4","d":"q","sl":true},{"p":"D4","d":"q","sl":true},{"p":"F4","d":"q"},{"p":"E4","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"F4","d":"q","sl":true},{"p":"A4","d":"q"},{"p":"G4","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"C5","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Thirds' AND kind = 'flexibility' AND notes = '[{"p":"C4","d":"q"},{"p":"E4","d":"q"},{"p":"D4","d":"q"},{"p":"F4","d":"q"},{"p":"E4","d":"q"},{"p":"G4","d":"q"},{"p":"F4","d":"q"},{"p":"A4","d":"q"},{"p":"G4","d":"q"},{"p":"B4","d":"q"},{"p":"A4","d":"q"},{"p":"C5","d":"q"},{"p":"C5","d":"w"}]'::jsonb;

-- Octave leaps: C4h^ C5h D4h^ D5h E4h^ E5h^ C4w
UPDATE warmup_exercises SET notes = '[{"p":"C4","d":"h","sl":true},{"p":"C5","d":"h"},{"p":"D4","d":"h","sl":true},{"p":"D5","d":"h"},{"p":"E4","d":"h","sl":true},{"p":"E5","d":"h","sl":true},{"p":"C4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Octave leaps' AND kind = 'flexibility' AND notes = '[{"p":"C4","d":"h"},{"p":"C5","d":"h"},{"p":"D4","d":"h"},{"p":"D5","d":"h"},{"p":"E4","d":"h"},{"p":"E5","d":"h"},{"p":"C4","d":"w"}]'::jsonb;

-- Broken chords: C4q^ E4q^ G4q^ C5q G4q^ E4q^ C4h F4q^ A4q^ C5q^ A4q^ F4w G4q^ B4q^ D5q^ B4q^ G4w C5w
UPDATE warmup_exercises SET notes = '[{"p":"C4","d":"q","sl":true},{"p":"E4","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"C5","d":"q"},{"p":"G4","d":"q","sl":true},{"p":"E4","d":"q","sl":true},{"p":"C4","d":"h"},{"p":"F4","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"F4","d":"w"},{"p":"G4","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"D5","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"G4","d":"w"},{"p":"C5","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Broken chords' AND kind = 'flexibility' AND notes = '[{"p":"C4","d":"q"},{"p":"E4","d":"q"},{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"q"},{"p":"E4","d":"q"},{"p":"C4","d":"h"},{"p":"F4","d":"q"},{"p":"A4","d":"q"},{"p":"C5","d":"q"},{"p":"A4","d":"q"},{"p":"F4","d":"w"},{"p":"G4","d":"q"},{"p":"B4","d":"q"},{"p":"D5","d":"q"},{"p":"B4","d":"q"},{"p":"G4","d":"w"},{"p":"C5","d":"w"}]'::jsonb;

-- Fourths and fifths: G4q^ C5q^ G4h A4q^ D5q^ A4h G4q^ D5q^ G4h C4q^ G4q^ C4h^ C4w
UPDATE warmup_exercises SET notes = '[{"p":"G4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"G4","d":"h"},{"p":"A4","d":"q","sl":true},{"p":"D5","d":"q","sl":true},{"p":"A4","d":"h"},{"p":"G4","d":"q","sl":true},{"p":"D5","d":"q","sl":true},{"p":"G4","d":"h"},{"p":"C4","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"C4","d":"h","sl":true},{"p":"C4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Fourths and fifths' AND kind = 'flexibility' AND notes = '[{"p":"G4","d":"q"},{"p":"C5","d":"q"},{"p":"G4","d":"h"},{"p":"A4","d":"q"},{"p":"D5","d":"q"},{"p":"A4","d":"h"},{"p":"G4","d":"q"},{"p":"D5","d":"q"},{"p":"G4","d":"h"},{"p":"C4","d":"q"},{"p":"G4","d":"q"},{"p":"C4","d":"h"},{"p":"C4","d":"w"}]'::jsonb;

-- Sixths: C4q^ A4q^ D4q^ B4q E4q^ C5q^ F4q^ D5q^ C5w
UPDATE warmup_exercises SET notes = '[{"p":"C4","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"D4","d":"q","sl":true},{"p":"B4","d":"q"},{"p":"E4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"F4","d":"q","sl":true},{"p":"D5","d":"q","sl":true},{"p":"C5","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Sixths' AND kind = 'flexibility' AND notes = '[{"p":"C4","d":"q"},{"p":"A4","d":"q"},{"p":"D4","d":"q"},{"p":"B4","d":"q"},{"p":"E4","d":"q"},{"p":"C5","d":"q"},{"p":"F4","d":"q"},{"p":"D5","d":"q"},{"p":"C5","d":"w"}]'::jsonb;

-- Expanding from C: C4q^ D4q^ C4h C4q^ E4q^ C4h C4q^ F4q^ C4h C4q^ G4q^ C4h^ C4w
UPDATE warmup_exercises SET notes = '[{"p":"C4","d":"q","sl":true},{"p":"D4","d":"q","sl":true},{"p":"C4","d":"h"},{"p":"C4","d":"q","sl":true},{"p":"E4","d":"q","sl":true},{"p":"C4","d":"h"},{"p":"C4","d":"q","sl":true},{"p":"F4","d":"q","sl":true},{"p":"C4","d":"h"},{"p":"C4","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"C4","d":"h","sl":true},{"p":"C4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Expanding from C' AND kind = 'flexibility' AND notes = '[{"p":"C4","d":"q"},{"p":"D4","d":"q"},{"p":"C4","d":"h"},{"p":"C4","d":"q"},{"p":"E4","d":"q"},{"p":"C4","d":"h"},{"p":"C4","d":"q"},{"p":"F4","d":"q"},{"p":"C4","d":"h"},{"p":"C4","d":"q"},{"p":"G4","d":"q"},{"p":"C4","d":"h"},{"p":"C4","d":"w"}]'::jsonb;

-- Broken chord in F: F4q^ A4q^ C5q^ F5q C5q^ A4q^ F4h Bb4q^ D5q^ F5q^ D5q^ Bb4w F4w
UPDATE warmup_exercises SET notes = '[{"p":"F4","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"C5","d":"q","sl":true},{"p":"F5","d":"q"},{"p":"C5","d":"q","sl":true},{"p":"A4","d":"q","sl":true},{"p":"F4","d":"h"},{"p":"Bb4","d":"q","sl":true},{"p":"D5","d":"q","sl":true},{"p":"F5","d":"q","sl":true},{"p":"D5","d":"q","sl":true},{"p":"Bb4","d":"w"},{"p":"F4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Broken chord in F' AND kind = 'flexibility' AND notes = '[{"p":"F4","d":"q"},{"p":"A4","d":"q"},{"p":"C5","d":"q"},{"p":"F5","d":"q"},{"p":"C5","d":"q"},{"p":"A4","d":"q"},{"p":"F4","d":"h"},{"p":"Bb4","d":"q"},{"p":"D5","d":"q"},{"p":"F5","d":"q"},{"p":"D5","d":"q"},{"p":"Bb4","d":"w"},{"p":"F4","d":"w"}]'::jsonb;

-- Arpeggio in G: G4q^ B4q^ D5q^ G5q D5q^ B4q^ G4h D4q^ G4q^ B4q^ D5q^ G4w
UPDATE warmup_exercises SET notes = '[{"p":"G4","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"D5","d":"q","sl":true},{"p":"G5","d":"q"},{"p":"D5","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"G4","d":"h"},{"p":"D4","d":"q","sl":true},{"p":"G4","d":"q","sl":true},{"p":"B4","d":"q","sl":true},{"p":"D5","d":"q","sl":true},{"p":"G4","d":"w"}]'::jsonb, updated_at = now()
 WHERE title = 'Arpeggio in G' AND kind = 'flexibility' AND notes = '[{"p":"G4","d":"q"},{"p":"B4","d":"q"},{"p":"D5","d":"q"},{"p":"G5","d":"q"},{"p":"D5","d":"q"},{"p":"B4","d":"q"},{"p":"G4","d":"h"},{"p":"D4","d":"q"},{"p":"G4","d":"q"},{"p":"B4","d":"q"},{"p":"D5","d":"q"},{"p":"G4","d":"w"}]'::jsonb;
